### ISSUE TITLE
ProMini16MHzv1.pdf contains an error

### ISSUE THREAD

**Issue by plainpylut** [sparkfun/Arduino_Pro_Mini_328#2]
I believe Pin 10, "PORT" identifier "PCB2" to be incorrect.  It should be "PB2".

**Comment by bboyho** [comment]
Hi,

I just checked the [Atmega328P datasheet on page 16](https://cdn.sparkfun.com/assets/1/1/9/c/b/Atmel-42735-8-bit-AVR-Microcontroller-ATmega328-328P_Datasheet.pdf). You are correct. =) Nice catch. I'll see what I can do as this is also linked in a different [repository](https://github.com/sparkfun/Graphical_Datasheets/tree/master/Datasheets), the other Pro Mini, and on the product pages.

**Comment by bboyho** [comment]
Fixed in this commit => [https://github.com/sparkfun/Arduino_Pro_Mini_328/commit/bcf8de441f8ebe9e21377c4a0d12794670dc2551](https://github.com/sparkfun/Arduino_Pro_Mini_328/commit/bcf8de441f8ebe9e21377c4a0d12794670dc2551)

I also updated the ones in the graphical datasheet here => [https://github.com/sparkfun/Graphical_Datasheets/commit/49f70e6a3971d1523a002636563cfd3526d1e41b](https://github.com/sparkfun/Graphical_Datasheets/commit/49f70e6a3971d1523a002636563cfd3526d1e41b) . I am looking into the product pages and tutorials. =)

**Comment by bboyho** [comment]
Product pages are updated with the correct links. Images in tutorials are updated as well. =)
